version: 2
formats: []

build:
  image: latest

sphinx:
  configuration: docs/conf.py

python:
  version: "3.8"
  install:
    - requirements: requirements.txt
    - requirements: docs/requirementsRTD.txt
    - method: pip
      path: .