name: mypy
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        pip install mypy
        pip install -r requirements.txt

    - name: Run mypy
      run: |
        mypy lavapy/